version: '3.8'

services:
  jarvis:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./setup:/app/setup
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PICOVOICE_ACCESS_KEY=${PICOVOICE_ACCESS_KEY}
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 